# Generated by Django 6.0.4 on 2026-04-24 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(help_text='Formato: +569XXXXXXXX', max_length=12, validators=[django.core.validators.RegexValidator(message='El teléfono debe estar en formato +569XXXXXXXX', regex='^\\+569\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(help_text='Formato: +569XXXXXXXX', max_length=12, validators=[django.core.validators.RegexValidator(message='El teléfono debe estar en formato +569XXXXXXXX', regex='^\\+569\\d{8}$')]),
        ),
    ]
