# Generated by Django 6.0.4 on 2026-04-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoriaservicio_alter_empresa_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadnegocio',
            name='tipo_impuesto',
            field=models.CharField(choices=[('afecto', 'Afecto a IVA'), ('exento', 'Exento')], default='exento', max_length=10),
        ),
    ]
