# Generated by Django 6.0.4 on 2026-04-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unidadnegocio_tipo_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(help_text='Valor en pesos chilenos. Ej: 230000'),
        ),
    ]
