# Generated by Django 6.0.4 on 2026-04-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='profesionales',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='core.profesional'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='sucursal_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='core.sucursal'),
        ),
    ]
