# Generated by Django 6.0.4 on 2026-04-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servicio_profesionales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('pendiente', 'Pendiente (no pagado)'), ('confirmado', 'Confirmado'), ('en_espera', 'En espera'), ('asistio', 'Asistió'), ('no_asistio', 'No asistió'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='reservado', max_length=20)),
                ('monto_total', models.PositiveIntegerField(default=0)),
                ('monto_pagado', models.PositiveIntegerField(default=0)),
                ('estado_pago', models.CharField(choices=[('sin_pago', 'Sin pago'), ('abonado', 'Abonado'), ('pagado', 'Pagado')], default='sin_pago', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_reprogramadas', to='core.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
