# Generated by Django 6.0.4 on 2026-04-24 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('activo', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tiene_descanso', models.BooleanField(default=False)),
                ('inicio_descanso', models.TimeField(blank=True, null=True)),
                ('fin_descanso', models.TimeField(blank=True, null=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.profesional')),
            ],
            options={
                'verbose_name': 'Horario profesional',
                'verbose_name_plural': 'Horarios profesionales',
                'unique_together': {('profesional', 'dia_semana')},
            },
        ),
    ]
