# Generated by Django 6.0.4 on 2026-04-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_horarioprofesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='dias_seguimiento',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de días para contactar nuevamente. Ej: 90 para Botox.', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='requiere_seguimiento',
            field=models.BooleanField(default=False),
        ),
    ]
