# Generated by Django 6.0.4 on 2026-04-27 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_servicio_dias_seguimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_objetivo', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('agendado', 'Agendado'), ('descartado', 'Descartado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.paciente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.servicio')),
            ],
            options={
                'verbose_name': 'Seguimiento de paciente',
                'verbose_name_plural': 'Seguimientos de pacientes',
                'ordering': ['fecha_objetivo'],
            },
        ),
    ]
