# Generated by Django 6.0.5 on 2026-05-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seguimientopaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('valor_fijo', 'Valor fijo ($)')], max_length=20)),
                ('valor', models.PositiveIntegerField(help_text='Si es %, ingresar 10 para 10%. Si es $, ingresar la cantidad.')),
                ('monto_descuento', models.PositiveIntegerField(help_text='Monto final a descontar en pesos')),
                ('razon', models.TextField(blank=True, help_text='Ej: Autorizado por Natalia Carro')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de autorización'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('solicitado_por', models.CharField(blank=True, max_length=100)),
                ('autorizado_por', models.CharField(blank=True, max_length=100)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='core.cita')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
