# Generated by Django 6.0.5 on 2026-05-17 01:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_insumo_and_commission_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['nombre'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.RenameIndex(
            model_name='comisioncalculada',
            new_name='core_comisi_profesi_a19f2c_idx',
            old_name='core_comisi_profesi_mes_idx',
        ),
        migrations.RenameIndex(
            model_name='comisioncalculada',
            new_name='core_comisi_mes_ref_590364_idx',
            old_name='core_comisi_mes_idx',
        ),
        migrations.AddField(
            model_name='comisioncalculada',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estructuracomision',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comisioncalculada',
            name='estructura_comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estructuracomision'),
        ),
        migrations.AlterField(
            model_name='comisioncalculada',
            name='mes_referencia',
            field=models.CharField(help_text='Formato YYYY-MM para agrupar por mes', max_length=7),
        ),
        migrations.AlterField(
            model_name='comisioncalculada',
            name='monto_comision',
            field=models.PositiveIntegerField(help_text='Comisión calculada para el profesional'),
        ),
        migrations.AlterField(
            model_name='comisioncalculada',
            name='monto_descuentos',
            field=models.PositiveIntegerField(default=0, help_text='Descuentos aplicados a la cita'),
        ),
        migrations.AlterField(
            model_name='comisioncalculada',
            name='monto_insumos',
            field=models.PositiveIntegerField(default=0, help_text='Costo total de insumos utilizados'),
        ),
        migrations.AlterField(
            model_name='comisioncalculada',
            name='porcentaje_comision',
            field=models.PositiveIntegerField(help_text='Porcentaje de comisión aplicado'),
        ),
        migrations.AlterField(
            model_name='estructuracomision',
            name='valor_comision',
            field=models.PositiveIntegerField(help_text='Para %, ingresar 30 para 30%. Para fijo, ingresar el monto en pesos.'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo_sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicioinsumo',
            name='cantidad_usada',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad de insumo usado por cada servicio', max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='estructuracomision',
            unique_together={('profesional', 'unidad_negocio', 'fecha_inicio')},
        ),
    ]
