# Generated by Django 6.0.5 on 2026-05-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_expand_insumo_estados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['-fecha_creacion', 'producto_proveedor__nombre'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.RenameIndex(
            model_name='insumo',
            new_name='core_insumo_unidad__068f4b_idx',
            old_name='core_insumo_unidad_negocio_fecha_creacion_idx',
        ),
        migrations.RenameIndex(
            model_name='insumo',
            new_name='core_insumo_estado_89ebd1_idx',
            old_name='core_insumo_estado_fecha_vencimiento_idx',
        ),
        migrations.RenameIndex(
            model_name='productoproveedor',
            new_name='core_produc_proveed_bbe40c_idx',
            old_name='core_productoproveedor_proveedor_activo_idx',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('terminado', 'Terminado')], default='vigente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['producto_proveedor', 'estado'], name='core_insumo_product_20583b_idx'),
        ),
    ]
