# Generated by Django 6.0.5 on 2026-05-23 21:36

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_insumo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinicaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, help_text='Medicamentos, materiales, alimentos. Una por línea.')),
                ('enfermedades_cronicas', models.TextField(blank=True, help_text='Hipertensión, diabetes, autoinmunes, etc.')),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Lista de medicamentos en uso (anticoagulantes son críticos).')),
                ('cirugias_previas', models.TextField(blank=True)),
                ('antecedentes_esteticos', models.TextField(blank=True, help_text='Tratamientos previos relevantes (ácido hialurónico, bótox, láser…)')),
                ('embarazo_lactancia', models.CharField(choices=[('no_aplica', 'No aplica'), ('embarazo', 'Embarazo en curso'), ('lactancia', 'Lactancia'), ('busca', 'Búsqueda activa')], default='no_aplica', max_length=20)),
                ('contraindicaciones', models.TextField(blank=True, help_text='Restricciones específicas para tratamientos (resaltadas en agenda).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_clinica', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Antecedentes clínicos',
                'verbose_name_plural': 'Antecedentes clínicos',
            },
        ),
        migrations.CreateModel(
            name='RegistroAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('motivo_consulta', models.TextField(blank=True, help_text='Razón por la que vino el paciente.')),
                ('procedimiento_realizado', models.TextField(help_text='Detalle del procedimiento o servicio realizado.')),
                ('productos_utilizados', models.TextField(blank=True, help_text='Producto, marca, lote, vencimiento, dosis. Crítico para trazabilidad.')),
                ('zonas_tratadas', models.CharField(blank=True, help_text='Ej: frente, ojos, mentón, glabela.', max_length=250)),
                ('parametros', models.TextField(blank=True, help_text='Energía, intensidad, número de pases, etc.')),
                ('observaciones', models.TextField(blank=True, help_text='Cómo respondió el paciente, eventos adversos, sensibilidad.')),
                ('indicaciones_post', models.TextField(blank=True, help_text='Indicaciones post-tratamiento entregadas al paciente.')),
                ('plan_proxima_sesion', models.TextField(blank=True, help_text='Qué se planifica para la próxima visita.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cita', models.OneToOneField(blank=True, help_text='Cita asociada (opcional — puede haber registros sin cita formal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_atencion', to='core.cita')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_atencion', to='core.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_atencion', to='core.profesional')),
            ],
            options={
                'verbose_name': 'Registro de atención',
                'verbose_name_plural': 'Registros de atención',
                'ordering': ['-fecha_atencion', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FotoEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=core.models._ruta_foto_evolucion)),
                ('tipo', models.CharField(choices=[('antes', 'Antes'), ('durante', 'Durante'), ('despues', 'Después'), ('control', 'Control'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('zona', models.CharField(blank=True, help_text='Ej: Frente, ojos, mentón.', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_evolucion', to='core.paciente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='core.registroatencion')),
            ],
            options={
                'verbose_name': 'Foto de evolución',
                'verbose_name_plural': 'Fotos de evolución',
                'ordering': ['-fecha', '-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('view', 'Visualización'), ('antecedentes_create', 'Creación de antecedentes'), ('antecedentes_update', 'Actualización de antecedentes'), ('registro_create', 'Creación de registro de atención'), ('registro_update', 'Actualización de registro de atención'), ('registro_delete', 'Eliminación de registro de atención'), ('foto_upload', 'Subida de foto'), ('foto_view', 'Visualización de foto'), ('foto_delete', 'Eliminación de foto')], max_length=30)),
                ('detalle', models.CharField(blank=True, help_text='Resumen humano de la acción.', max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_ficha', to='core.paciente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_ficha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de ficha clínica',
                'verbose_name_plural': 'Log de fichas clínicas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['paciente', '-timestamp'], name='core_auditl_pacient_a248a2_idx'), models.Index(fields=['usuario', '-timestamp'], name='core_auditl_usuario_019257_idx')],
            },
        ),
    ]
