# Generated by Django 6.0.5 on 2026-05-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_fichaclinicapaciente_registroatencion_fotoevolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatencion',
            name='aparatologia',
            field=models.TextField(blank=True, help_text="Equipos/máquinas utilizadas (ej: Luna Box, láser diodo). Los parámetros técnicos van en el campo 'parametros'."),
        ),
        migrations.AddField(
            model_name='registroatencion',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Servicio del catálogo aplicado (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_atencion', to='core.servicio'),
        ),
    ]
