# Generated by Django 6.0.5 on 2026-05-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_registroatencion_aparatologia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número del box (1, 2, 3...). Único por sucursal.')),
                ('nombre', models.CharField(help_text="Ej: 'Box 1 - Sala de Procedimientos', 'Box 10 - Ginecología'", max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles del equipamiento o características especiales.')),
                ('es_acceso_universal', models.BooleanField(default=False, help_text='Box accesible para cualquier profesional/servicio (ej: Box 11).')),
                ('fecha_inicio_uso', models.DateField(blank=True, help_text='Si el box recién empieza a usarse desde una fecha específica.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('profesionales_habituales', models.ManyToManyField(blank=True, help_text='Profesionales que típicamente usan este box.', related_name='boxes_habituales', to='core.profesional')),
                ('servicios_disponibles', models.ManyToManyField(blank=True, help_text='Servicios que se pueden realizar en este box.', related_name='boxes_disponibles', to='core.servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Box de atención',
                'verbose_name_plural': 'Boxes de atención',
                'ordering': ['sucursal', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='core.box'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('sucursal', 'numero'), name='unique_box_numero_por_sucursal'),
        ),
    ]
