# Generated by Django 6.0.5 on 2026-05-24 21:35
# Data migration: precarga los 11 boxes reales de Clínica Mía Salud
# Fuente: documento "DISTRIBUCIÓN DE BOX Y PRESTACIONES.docx" (24 mayo 2026)
# Las relaciones M2M (profesionales, servicios) se asignan manualmente
# desde la UI porque dependen de qué prof/serv estén realmente en la BD.

from datetime import date
from django.db import migrations


BOXES_SEED = [
    {
        'numero': 1,
        'nombre': 'Box 1 — Sala de Procedimientos',
        'descripcion': 'Carolina Carmona (Cosmetología) + Dr Claudio Rodriguez (Armonización Facial). '
                       'Servicios: PRP, Peeling, Fixer Plas, Mesoterapia, IPL Fraclight, Fototerapia, '
                       'Microneedling, Crioterapia, Botox, Ácido hialurónico.',
    },
    {
        'numero': 2,
        'nombre': 'Box 2 — Sala de Procedimientos + Botiquín',
        'descripcion': 'Dra Paola Bonaldi (Dermatología) + Dra María José Moyano (Armonización Facial). '
                       'Incluye botiquín equipado. Bioestimuladores, Lipolax VL, Fixer Glow, '
                       'Mesoterapia Pink Glow además del set base.',
    },
    {
        'numero': 3,
        'nombre': 'Box 3 — Sala de Procedimientos',
        'descripcion': 'Dra Paola Bonaldi + Dr Vittorio Zaffiri. Dermatología/Cosmetología completa '
                       'y Armonización Facial.',
    },
    {
        'numero': 4,
        'nombre': 'Box 4 — Multidisciplinar',
        'descripcion': 'Daniela Maldonado (Kinesióloga) + Dr Vittorio Zaffiri (Enfermería). '
                       'Evaluaciones kinesiológicas, Depilación láser, Peeling químico, '
                       'Limpiezas faciales, Fototerapia.',
    },
    {
        'numero': 5,
        'nombre': 'Box 5 — Cosmetología',
        'descripcion': 'María José Uribe. Evaluaciones cosmetológicas, Peeling químico, '
                       'Limpiezas faciales, Fototerapia.',
    },
    {
        'numero': 6,
        'nombre': 'Box 6 — Nutrición + Holístico',
        'descripcion': 'Ignacio Diaz + Nutricionistas. Consultas nutricionales, terapias holísticas, '
                       'masajes descontracturantes y de relajación.',
    },
    {
        'numero': 7,
        'nombre': 'Box 7 — Corporales y Kinesiología',
        'descripcion': 'Daniela Maldonado. Tensamax, HIFU, Drenajes linfáticos, '
                       'Masajes (relajación / post-operatorios).',
    },
    {
        'numero': 8,
        'nombre': 'Box 8 — Consultas',
        'descripcion': 'Dra Paola Bonaldi. Consultas dermatológicas y otras consultas médicas.',
    },
    {
        'numero': 9,
        'nombre': 'Box 9 — Oftalmología',
        'descripcion': 'Dr Cristiano Burela. Consultas oftalmológicas.',
    },
    {
        'numero': 10,
        'nombre': 'Box 10 — Procedimientos Ginecológicos',
        'descripcion': 'Dra Migdalia + Dr Hector Pinto. Consultas, Toma PAP, PRP vulvar, '
                       'Extirpaciones ginecológicas menores, Anticonceptivos, Evaluación ITS.',
        'fecha_inicio_uso': date(2026, 5, 29),  # según el documento
    },
    {
        'numero': 11,
        'nombre': 'Box 11 — Acceso Universal',
        'descripcion': 'Dra Paulina Cerda (Medicina General). Box equipado para todos los servicios '
                       'de dermatología, cosmetología y armonización facial. Acceso transversal.',
        'es_acceso_universal': True,
    },
]


def crear_boxes_iniciales(apps, schema_editor):
    """Crea los 11 boxes en la primera sucursal activa de la primera empresa."""
    Sucursal = apps.get_model('core', 'Sucursal')
    Box = apps.get_model('core', 'Box')

    sucursal = Sucursal.objects.filter(activa=True).first()
    if not sucursal:
        # Si todavía no hay sucursal, no hacemos nada — el admin los creará a mano
        return

    for data in BOXES_SEED:
        Box.objects.get_or_create(
            sucursal=sucursal,
            numero=data['numero'],
            defaults={
                'nombre': data['nombre'],
                'descripcion': data.get('descripcion', ''),
                'es_acceso_universal': data.get('es_acceso_universal', False),
                'fecha_inicio_uso': data.get('fecha_inicio_uso'),
                'activo': True,
            }
        )


def eliminar_boxes_iniciales(apps, schema_editor):
    """Reversa: borra los boxes por número."""
    Box = apps.get_model('core', 'Box')
    Box.objects.filter(numero__in=[b['numero'] for b in BOXES_SEED]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_box_cita_box_box_unique_box_numero_por_sucursal'),
    ]

    operations = [
        migrations.RunPython(crear_boxes_iniciales, eliminar_boxes_iniciales),
    ]
